//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_CV_Prj.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASPCVProjectEntities1 : DbContext
    {
        public ASPCVProjectEntities1()
            : base("name=ASPCVProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abilities> Abilities { get; set; }
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Experiences> Experiences { get; set; }
        public virtual DbSet<Interests> Interests { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<SocialMediaLinks> SocialMediaLinks { get; set; }
        public virtual DbSet<Portfolio> Portfolio { get; set; }
        public virtual DbSet<Tools> Tools { get; set; }
    }
}
