//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_CV_Prj.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tools
    {
        public int ID { get; set; }
        public int Star { get; set; }
        public string Details { get; set; }
    }
}
